### PR TITLE
Remove redundant `JumpKicker` folder from root.

### LINKED ISSUE #6: Remove `JumpKicker` folder from root directory.
Is there a specific reason why we have two root directories?

Our root directory should be what `JumpKicker` is. So we really want `JumpKicker`'s contents in our root directory and not have to jump through an extra directory.

We can also move this to a repo named "JumpKicker", too.

### PR DESCRIPTION
**Pull request by kWhittington**
`JumpKicker` acted like a second root directory and we'd like to keep
the file system as simple as possible. All of `JumpKicker`'s contents
were moved into the root directory.

Closes #6

### CODE REVIEW

**Comment by kWhittington** [comment]
@poker158149 please confirm Unity reads this file structure no differently than it would the project in `master`. It looks good to me.

**Comment by kWhittington** [comment]
If this solution worked, all you need to do is move all files in `JumpKicker` (including the `.gitignore`) and move them into its parent directory. Then delete `JumpKicker`. Your branch should be good to go then.

**Comment by parkersprouse** [comment]
@kWhittington After moving the files up a directory and deleting the `JumpKicker` directory, Unity still sees the project as a complete project and git painlessly let me push it to the repo with the new structure. All is well on my end.

**Comment by kWhittington** [comment]
Sweet. We can kill this branch or merge it into `master`.

**Comment by parkersprouse** [comment]
We should definitely merge it into `master` so that everything can be based on this new structure.

**Comment by kWhittington** [comment]
Kool. @HeLooksAngry, you kool with this merge?

**Comment by kWhittington** [comment]
Instructions for renaming a GitHub repo: http://zanshin.net/2012/04/03/renaming-github-repository/

**Pull request merged**
